version: "4"
services:
 mysql: 
  image: mysql:8.3.0
  container_name: mysql_bikerental_app
  environment:
   MYSQL_ROOT_PASSWORD: Dreamteam@1302
  ports: 
   - "3308:3306"
  volumes: 
   - ./mysql:/var/lib/mysql
   - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql